In [1]:
import glob, os
import pandas as pd
import numpy as np

In [3]:
df_gameresults = pd.read_csv('Project Data/Game_results18-19.csv', parse_dates=True)
df_gameresults['Season'] = '2018/2019'

In [5]:
df_gameresults['Unnamed: 7'] = df_gameresults['Unnamed: 7'].apply(lambda x: 1 if x == 'OT' else (2 if x == '2OT' else (3 if x == '3OT'
                                          else (4 if x == '4OT' else 0))))
df_gameresults.rename(columns={'Unnamed: 7':'Overtime', 'PTS':'Visitor-Points', 'PTS.1':'Home-Points'}, inplace=True)
df_gameresults = df_gameresults.drop(['Unnamed: 6', 'Notes'], 1)

,Date,Start (ET),Visitor/Neutral,Visitor-Points,Home/Neutral,Home-Points,Overtime,Attend.,Season
0,Tue Oct 16 2018,8:00p,Philadelphia 76ers,87,Boston Celtics,105,0,18624.0,2018/2019
1,Tue Oct 16 2018,10:30p,Oklahoma City Thunder,100,Golden State Warriors,108,0,19596.0,2018/2019
2,Wed Oct 17 2018,7:00p,Milwaukee Bucks,113,Charlotte Hornets,112,0,17889.0,2018/2019
3,Wed Oct 17 2018,7:00p,Brooklyn Nets,100,Detroit Pistons,103,0,20332.0,2018/2019
4,Wed Oct 17 2018,8:00p,New Orleans Pelicans,131,Houston Rockets,112,0,18055.0,2018/2019

In [6]:
df_gameresults.sample(10)

,Date,Start (ET),Visitor/Neutral,Visitor-Points,Home/Neutral,Home-Points,Overtime,Attend.,Season
77,Sat Oct 27 2018,8:00p,Portland Trail Blazers,111,Miami Heat,120,0,19600.0,2018/2019
52,Wed Oct 24 2018,8:00p,Charlotte Hornets,110,Chicago Bulls,112,0,19170.0,2018/2019
70,Fri Oct 26 2018,7:30p,Golden State Warriors,128,New York Knicks,100,0,19812.0,2018/2019
50,Tue Oct 23 2018,8:00p,Los Angeles Clippers,109,New Orleans Pelicans,116,0,14625.0,2018/2019
15,Thu Oct 18 2018,8:00p,Miami Heat,113,Washington Wizards,112,0,20409.0,2018/2019
32,Sat Oct 20 2018,7:30p,Orlando Magic,115,Philadelphia 76ers,116,0,20300.0,2018/2019
33,Sat Oct 20 2018,10:00p,San Antonio Spurs,108,Portland Trail Blazers,121,0,19461.0,2018/2019
39,Mon Oct 22 2018,7:30p,Orlando Magic,93,Boston Celtics,90,0,18624.0,2018/2019
43,Mon Oct 22 2018,8:00p,New York Knicks,113,Milwaukee Bucks,124,0,16228.0,2018/2019
46,Mon Oct 22 2018,7:30p,Charlotte Hornets,106,Toronto Raptors,127,0,19800.0,2018/2019

In [11]:
dfM = pd.read_csv('Project Data/M_table18-19.csv')
dfM.columns = dfM.iloc[0]
dfM['Season']='2018/2019'
dfM = dfM[dfM.Team != 'Team']
dfM = dfM[dfM.Team != 'League Average']
dfM.Team = dfM.Team.str.replace('*','')
dfM['Team'] = dfM['Team'].apply(lambda x: 'Charlotte Hornets' if x == 'Charlotte Bobcats' else x)
dfM = dfM.drop(['Rk', 'Arena', 'Attend.', 'Attend./G'], 1)
dfM.columns.values[15] = "OeFG%"
dfM.columns.values[16] = "OTOV%"
dfM.columns.values[17] = "ODRB%"
dfM.columns.values[18] = "OFT/FGA"
dfM.columns.values[19] = "DeFG%"
dfM.columns.values[20] = "DTOV%"
dfM.columns.values[21] = "DDRB%"
dfM.columns.values[22] = "DFT/FGA"

In [12]:
dfM.sample(5)

,Team,Age,W,L,PW,PL,MOV,SOS,SRS,ORtg,...,TS%,OeFG%,OTOV%,ODRB%,OFT/FGA,DeFG%,DTOV%,DDRB%,DFT/FGA,Season
5,Charlotte Hornets,26.8,5,5,7,3,7.60,-0.88,6.72,116.5,...,.574,.536,10.6,23.6,.195,.517,12.6,77.9,.206,2018/2019
27,Dallas Mavericks,26.3,2,7,3,6,-6.00,-2.67,-8.67,108.3,...,.552,.520,14.0,24.3,.190,.570,14.0,80.2,.231,2018/2019
3,Denver Nuggets,24.8,8,1,7,2,9.56,-0.94,8.61,112.1,...,.551,.514,12.1,27.5,.213,.505,14.0,79.9,.197,2018/2019
21,Detroit Pistons,27.3,4,4,3,5,-2.63,-2.28,-4.90,106.1,...,.526,.482,11.9,24.3,.232,.517,11.9,82.4,.254,2018/2019
22,Houston Rockets,29.8,3,5,3,5,-5.88,0.89,-4.99,107.2,...,.528,.499,11.5,24.2,.175,.535,12.9,78.0,.248,2018/2019

In [17]:
dfO = pd.read_csv('Project Data/O_table18-19.csv')
dfO['Season']='2018/2019'
dfO.Team = dfO.Team.str.replace('*','')
dfO = dfO[dfO.Team != 'League Average']
dfO['Team'] = dfO['Team'].apply(lambda x: 'Charlotte Hornets' if x == 'Charlotte Bobcats' else x)
dfO = dfO.drop(['Rk'], 1)
dfO = dfO.add_prefix('O_')

In [18]:
dfO.sample(5)

,O_Team,O_G,O_MP,O_FG,O_FGA,O_FG%,O_3P,O_3PA,O_3P%,O_2P,...,O_ORB,O_DRB,O_TRB,O_AST,O_STL,O_BLK,O_TOV,O_PF,O_PTS,O_Season
16,Portland Trail Blazers,9,242.8,41.4,94.6,0.438,10.4,30.9,0.338,31.0,...,12.4,33.6,46.0,22.8,7.1,6.7,12.0,22.6,110.8,2018/2019
27,Golden State Warriors,10,240.0,39.8,90.9,0.438,12.5,38.7,0.323,27.3,...,10.6,30.5,41.1,23.1,8.2,2.9,13.4,20.6,110.6,2018/2019
7,Miami Heat,8,240.0,40.8,89.1,0.457,11.5,30.6,0.376,29.3,...,9.5,33.1,42.6,23.0,7.1,8.3,12.5,25.1,112.3,2018/2019
28,Philadelphia 76ers,10,242.5,40.9,94.6,0.432,10.5,32.7,0.321,30.4,...,9.5,36.9,46.4,22.9,6.9,5.9,13.1,23.8,112.0,2018/2019
14,Los Angeles Clippers,9,240.0,39.8,92.9,0.428,9.1,27.2,0.335,30.7,...,11.6,33.1,44.7,21.7,8.6,6.0,12.0,25.6,109.9,2018/2019

In [20]:
dfT = pd.read_csv('Project Data/T_table18-19.csv')
dfT['Season']='2018/2019'
dfT.Team = dfT.Team.str.replace('*','')
dfT = dfT[dfT.Team != 'League Average']
dfT['Team'] = dfT['Team'].apply(lambda x: 'Charlotte Hornets' if x == 'Charlotte Bobcats' else x)
dfT = dfT.drop(['Rk'], 1)
dfT = dfT.add_prefix('T_')

In [21]:
dfT.sample(5)

,T_Team,T_G,T_MP,T_FG,T_FGA,T_FG%,T_3P,T_3PA,T_3P%,T_2P,...,T_ORB,T_DRB,T_TRB,T_AST,T_STL,T_BLK,T_TOV,T_PF,T_PTS,T_Season
14,Dallas Mavericks,9,242.8,40.8,90.1,0.453,12.1,35.6,0.341,28.7,...,10.9,32.3,43.2,23.8,6.9,4.7,16.3,21.8,110.8,2018/2019
15,Utah Jazz,9,240.0,38.7,83.4,0.463,11.4,32.0,0.358,27.2,...,9.8,33.8,43.6,23.2,7.9,5.4,15.2,22.4,109.8,2018/2019
9,Toronto Raptors,9,240.0,43.8,90.6,0.483,11.8,33.3,0.353,32.0,...,10.2,36.1,46.3,26.0,8.4,6.6,13.0,22.9,116.2,2018/2019
16,Brooklyn Nets,9,242.8,40.0,87.2,0.459,13.8,35.6,0.388,26.2,...,10.3,33.4,43.8,24.7,5.8,4.8,15.8,22.6,108.6,2018/2019
17,New York Knicks,9,240.0,40.2,90.9,0.443,10.7,30.6,0.349,29.6,...,11.1,31.6,42.7,20.2,7.9,3.0,13.1,21.4,107.3,2018/2019

In [23]:
df_new = pd.merge(df_gameresults, dfM, how='left', left_on=['Visitor/Neutral','Season'], right_on = ['Team','Season'])
df_new = pd.merge(df_new, dfM, how='left', left_on=['Home/Neutral','Season'], right_on = ['Team','Season'])
df_new = df_new.drop(['Team_x', 'Team_y'], 1)

In [24]:
df_new.sample(5)

,Date,Start (ET),Visitor/Neutral,Visitor-Points,Home/Neutral,Home-Points,Overtime,Attend.,Season,Age_x,...,3PAr_y,TS%_y,OeFG%_y,OTOV%_y,ODRB%_y,OFT/FGA_y,DeFG%_y,DTOV%_y,DDRB%_y,DFT/FGA_y
18,Fri Oct 19 2018,8:00p,Atlanta Hawks,117,Memphis Grizzlies,131,0,17019.0,2018/2019,26.0,...,.350,.557,.512,11.6,17.4,.257,.524,16.0,76.5,.202
78,Sat Oct 27 2018,8:30p,Orlando Magic,91,Milwaukee Bucks,113,0,17341.0,2018/2019,25.6,...,.432,.593,.561,14.1,22.6,.192,.461,10.0,80.1,.165
34,Sat Oct 20 2018,7:00p,Toronto Raptors,117,Washington Wizards,113,0,16185.0,2018/2019,27.6,...,.388,.552,.505,12.9,17.5,.239,.553,13.1,70.9,.227
59,Wed Oct 24 2018,10:00p,Memphis Grizzlies,92,Sacramento Kings,97,0,14198.0,2018/2019,28.1,...,.285,.582,.560,12.1,21.7,.187,.530,14.2,76.0,.208
32,Sat Oct 20 2018,7:30p,Orlando Magic,115,Philadelphia 76ers,116,0,20300.0,2018/2019,25.6,...,.378,.549,.502,12.7,22.3,.243,.488,11.0,80.6,.208

In [25]:
df_new = pd.merge(df_new, dfO, how='left', left_on=['Visitor/Neutral','Season'], right_on = ['O_Team','O_Season'])
df_new = pd.merge(df_new, dfO, how='left', left_on=['Home/Neutral','Season'], right_on = ['O_Team','O_Season'])
df_new = pd.merge(df_new, dfT, how='left', left_on=['Visitor/Neutral','Season'], right_on = ['T_Team','T_Season'])
df_new = pd.merge(df_new, dfT, how='left', left_on=['Home/Neutral','Season'], right_on = ['T_Team','T_Season'])
df_new = df_new.drop(['O_Team_x', 'O_Team_y', 'T_Team_x', 'T_Team_y',
                      'O_Season_x', 'O_Season_y', 'T_Season_x', 'T_Season_y'], 1)
df_new.columns = [c.replace('_x', '_Visitor') for c in df_new.columns]
df_new.columns = [c.replace('_y', '_Home') for c in df_new.columns]

In [26]:
df_new.sample(5)

,Date,Start (ET),Visitor/Neutral,Visitor-Points,Home/Neutral,Home-Points,Overtime,Attend.,Season,Age_Visitor,...,T_FT%_Home,T_ORB_Home,T_DRB_Home,T_TRB_Home,T_AST_Home,T_STL_Home,T_BLK_Home,T_TOV_Home,T_PF_Home,T_PTS_Home
53,Wed Oct 24 2018,7:00p,Brooklyn Nets,102,Cleveland Cavaliers,86,0,19432.0,2018/2019,25.3,...,0.830,12.2,29.2,41.4,20.7,8.0,1.8,14.0,22.2,106.1
74,Sat Oct 27 2018,7:30p,Indiana Pacers,119,Cleveland Cavaliers,107,0,19432.0,2018/2019,26.9,...,0.830,12.2,29.2,41.4,20.7,8.0,1.8,14.0,22.2,106.1
75,Sat Oct 27 2018,7:00p,Boston Celtics,109,Detroit Pistons,89,0,18120.0,2018/2019,25.8,...,0.746,11.9,36.3,48.1,18.8,5.4,4.1,14.0,25.3,109.5
47,Mon Oct 22 2018,9:00p,Memphis Grizzlies,92,Utah Jazz,84,0,18306.0,2018/2019,28.1,...,0.738,9.8,33.8,43.6,23.2,7.9,5.4,15.2,22.4,109.8
23,Fri Oct 19 2018,8:00p,Boston Celtics,101,Toronto Raptors,113,0,19800.0,2018/2019,25.8,...,0.768,10.2,36.1,46.3,26.0,8.4,6.6,13.0,22.9,116.2

In [27]:
df_new.to_csv('test_data.csv', index=False)